name: "Building & push docker image for master branch xxx"
on:
  push:
    branches:
    - master

jobs:
  build_images:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: "Checking out the repository"
        uses: actions/checkout@v2

      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      

      - name: "Calculating docker image tag"
        id: version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: "build the docker containers"        
        run: |
          docker-compose build

      - name: "Log in to docker hub"
        uses: azure/docker-login@v1
        if: github.repository == 'geobretagne/mreport'
        with:
          username: '${{ secrets.DOCKER_HUB_USERNAME }}'
          password: '${{ secrets.DOCKER_HUB_PASSWORD }}'      

      - name: List images
        run: docker images
      
      - name: Push images
        run: docker-compose push --ignore-push-failures      
      
